# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: xk5dzDoDeiiknAsuPBwzqwFyLAupQEYh
            client-secret: uypzZu8n2f-_Z0XH6xpre-yOS8fJ7DfPFXF5LJj6ypo71PmgIWqshNy9Rhk6jM-l
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-we51wzjgmx6v0f6c.us.auth0.com/

